version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - psql-data:/var/lib/postgresql/data
      - .:/application
    ports:
      - "5003:5432"

  app:
    build: .
    working_dir: /application/server
    env_file:
      - .env
    command: "tail -f /dev/null"
    #     command: ["python", "manage.py", "runserver", "0:9001"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.8/site-packages
      - app-usr-local-bin:/usr/local/bin
      - ~/.ssh:/root/.ssh
    ports:
      - "9003:9003"
    depends_on:
      - db

volumes:
  app-python-site-packages:
    driver: local
  psql-data:
    driver: local
  app-usr-local-bin:
    driver: local

