# Generated by Django 4.2.7 on 2023-11-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='used',
            new_name='is_active',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
